export const CREATE_COURSE = "CREATE_COURSE"
export const LOAD_COURSE = "LOAD_COURSE"

export const LOAD_AUTHORS = "LOAD_AUTHORS"
export const UPDATE_COURSE_FORM = "UPDATE_COURSE"
export const CREATE_COURSE_FORM = "CREATE_COURSE"

